### ISSUE TITLE
Complete a keygen happy path ceremony in axelar-core using rust-tssd

### ISSUE THREAD

**Issue by ggutoski** [axelarnetwork/tofnd#1]
Current status of rust-tssd is a prototype keygen happy path passing only a minimal test.  Next goal is the title: Complete a keygen happy path ceremony in axelar-core using rust-tssd.

## Tasks
- [ ] Golang client for rust-tssd.  I currently have a local golang rust-tssd client repo for rust-tssd with a basic test---this repo should be moved into the rust-tssd repo itself.  
- [ ] Better tests: golang client, rust-tssd, thrush.
- [ ] thrush, rust-tssd should never panic---return errors instead.
- [ ] Rust-tssd does not yet store keys it generates.  Add a KV store for (pubkey_name, pubkey_data).  Need to search for a good KV store rust library.
- [ ] Swap rust-tssd into axelar-core, run a ceremony.  Prerequisite: figure out the deserialization needs of the resulting pubkey in axelar-core.
- [ ] Code review?

**Comment by neocho** [comment]
Hey ggutoski! Do you still have the go-tofnd-client to try out?
