### ISSUE TITLE
Epic: mainnet must-haves

### ISSUE THREAD

**Issue by ggutoski** [axelarnetwork/tofnd#10]
Migrated from [Tss checklist notion doc](https://www.notion.so/Tss-checklist-89409329df604dbebb5d38bd7379e73d).

- [x] fault attribution
  - [x]  easy faults
  - [x]  hard faults, requiring additional rounds of msgs
  - [x]  deserialization faults
  - [x]  timeouts
  - [x]  tests
  - _Design note:_ Begin each round with a list of messages received from other parties.  3 states: timeout (or other declared failure), deserialization failure, or successfully deserialized message.
- [x] multiple shares per validator for stake-weighted threshold crypto
- [ ] authentication of messages (Stelios)
  - [ ] in axelar-core axelarnetwork/axelar-core#157
  - [x] in tofnd #60 
  - [x] in tofn axelarnetwork/tofn#42
- [ ] tofn, tofnd should never panic (Stelios?)
- [x] use sled for KV store (done in #15)
- [x] better handling of test files. (done in #18)
- [x] Eliminate use of zengo crates. Use k256 for math. axelarnetwork/tofn#58
- [ ] check for places where we need secure erasures of secrets in memory 
- [x] research logging libraries, choose one and deploy it in tofn and tofnd. #19 
- [x] Sad path should return specific crimes axelarnetwork/tofn#44
- [ ] check the tofn, tofnd APIs to make sure no leakage of secrets is allowed via various queries, "injection attacks" (put a command inside some field to trigger a malicious behavior), etc. 

## Keygen enhancements

- [x] safe primes axelarnetwork/tofn#18
- [ ] key share recovery from mnemonic
  - [ ] axelar-core
  - [x] tofnd
  - [x] tofn (done in axelarnetwork/tofn#80 )
- [x] encrypt p2p keygen traffic axelarnetwork/tofn#17
- [x] Keygen zk proofs for Paillier keys axelarnetwork/tofn#74

## Nice to have but not needed for mainnet

- [ ] robust keygen: new protocol design.  (Do we want robust sign, too?)
- [ ] Useful error messages and context. #28
- [x] Eliminate confusion on party vs participant indices axelarnetwork/tofn#11
- [ ] git submodule for shared protobuf file #9 
  - [x] tofnd: done in #64 
  - [ ] axelar-core: TODO
- [ ] do not store party IDs in tofnd axelarnetwork/axelar-core#171
- [ ] Switch from GG20 to CGGMP
