### ISSUE TITLE
Address observations and notes from tofnd audit

### ISSUE THREAD

**Issue by sdaveas** [axelarnetwork/tofnd#147]
# Findings
1. Insufficient Validation during Key Recovery
    - [x] #152

# Notes and observations
1. Validation of party-uids and new_key_uid for [a-z][A-Z][0-9]
    - [x] into want extend do we need this? We surely don't want to include non-printable characters but "!@#$%^&*()" might be fine. Could be addressed in #143.
2. Inconsistent use of signed/unsigned integers https://github.com/axelarnetwork/tofnd/blob/main/src/gg20/keygen/init.rs#L89-L90
    - [x] these need to change at the protofile. We have no access to tonic's structs. https://github.com/axelarnetwork/grpc-protobuf/blob/main/grpc.proto#L112-L113
3. Maximum number of shares per party https://github.com/axelarnetwork/tofnd/blob/main/src/gg20/keygen/mod.rs#L70-L71
    - [x] #205 
4. Incomplete validation of `GroupPublicInfo` in secret_key_shares. 
    - [x] check other contents of `GroupPublicInfo`, such as `party_share_counts`, `threshold`, `all_shares`. This will be partially touched at https://github.com/axelarnetwork/tofnd/issues/146, although these are mostly sanity checks for correct protocol execution
5. Maximum number of threads in tokio runtime. https://github.com/axelarnetwork/tofnd/blob/main/src/main.rs#L47
    - [x] related issue: https://github.com/axelarnetwork/tofnd/issues/58 in which tests crash with `num_threads` < 4.
6. Confusion between session ID vs. key UID. 
     * there is a relevant comment [here](https://github.com/axelarnetwork/tofnd/blob/main/src/gg20/keygen/types.rs#L25), but surely naming can be improved
     * #203 

# Possible false positives

## Findings
1. Insufficient Validation during Key Recovery
    * We do not allow to overwrite an existing key because `reserve_key` returns an error https://github.com/axelarnetwork/tofnd/blob/main/src/gg20/recover.rs#L159

## Notes and observations
1. Size of `message_to_sign` in sign.
    * Check is done: https://github.com/axelarnetwork/tofnd/blob/main/src/gg20/sign/init.rs#L96
    * unit test: https://github.com/axelarnetwork/tofnd/blob/main/src/gg20/sign/init.rs#L155
    * the `TODO` in  https://github.com/axelarnetwork/tofnd/blob/main/src/tests/mod.rs#L43. refers to potentially add the same test in the integration tests
2. Assert macros are included in release builds
    * didn't find any `assert` in tofnd's production code
