### ISSUE TITLE
implement sign in tofn

### ISSUE THREAD

**Issue by ggutoski** [axelarnetwork/tofnd#6]
## Goal

- [ ] Implement sign happy path in tofn. (Then: add sign to tofnd, complete a sign ceremony, etc.)

## Tasks

- [ ] KV store for tofnd
- [ ] encrypt sensitive traffic in tofn
- [ ] authentication in axelar-core (see axelarnetwork/axelar-core#157 )
- [ ] tofn, tofnd should never panic
- [ ] design change: merge stateless functions into stateful
